### PR TITLE
(Docs) Fix broken link to service file

### PR DESCRIPTION
**Pull request by hestonhoffman**
Fixes a broken link on the README page.

**Checklist**

- [ ] Added tests (if necessary)
- [x] Updated docs or README...

### CODE REVIEW

**Comment by hestonhoffman** [comment]
I assumed this was the right service file cos it's the only one I could find in then repo, but looking at it again, I might be wrong :sweat_smile:

**Comment by joshgoebel** [comment]
Really this isn't very fleshed out yet - I don't know that a lot of people are using it from systemd... but perhaps that link would be better than the current broken one?  Are you using it as a service with this service file?

**Comment by hestonhoffman** [comment]
I gave it a shot, but I couldn't get it working. I ended up just throwing `keyszer &` in my autostart script and that works great. Perhaps it would be better to remove that sentence from the README for now.

**Comment by RedBearAK** [comment]
@joshgoebel 

Should be able to close this PR, since it's basically the same as #139 that was just approved/merged, to fix the link to the service file example.

**Pull request closed without merging**
