### PR TITLE
(enh) adds `include` support for config files

### LINKED ISSUE #30: Allow requiring other config files from the main config for better oganization
Other than the main reason (adding custom keybindings that don't get ovewritten with a new kinto.py)...

This might be important for those with foreign keymappings  needed to do large customization to find the perfect fir of Kinto & their keyboard.

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolves #30.

### `include(relative_filename)`

Include a sub-configuration file into the existing config.  This file is loaded and executed at the point of inclusion and shares the same global scope as the existing config. These files should be present in the same directory as your main configuration.

```py
include("os.py")
include("apps.py")
include("deadkeys.py")
```

**Checklist**

- [ ] Added tests (if necessary)
- [x] Updated docs or README...

### CODE REVIEW

**Comment by joshgoebel** [comment]
@RedBearAK @rbreaves You all might be interested.

**Comment by RedBearAK** [comment]
@joshgoebel 

I was literally just thinking about trying a simple version of this a couple of days ago, what with my contributions to the Kinto config getting so lengthy. This looks great. If I'm understanding the changes the included files will be checked before being pulled in, or will that only be when using the check flag? Either way it looks like there's some good logging info there. 

At some point I would like to see the code also attempt to throw up a GUI notification if an include failed, using `notify-send`. I know it's not completely universal on Linux desktops, but it's usually present on all the popular "desktop" distros, and it would be helpful to have some GUI feedback when something happens that requires the user to check the log and fix something.

**Comment by joshgoebel** [comment]
> If I'm understanding the changes the included files will be checked before being pulled in,

The config (and includes) are read and evaluated always... `--check` is just for scripting niceness to ask us to check the config... if there is a Python error in the config itself Keyszer will crash with a stacktrace (or with `--check` return a non-zero error code).

> At some point I would like to see the code also attempt to throw up a GUI notification if an include failed, using notify-send. 

I'm pretty dead-set against spawning any sub-processes/shells and have already laid out the architecture I believe should be used for any GUI endeavors: #44   

Of course it's easy to ignore me and do whatever one wants in the config (gotta love it)... but I'm not currently interesting in encouraging this (outside of the architecture defined in #44).

Regarding this request individually personally I think a GUI error for a console program failing to start-up is a bit weird.

**Comment by joshgoebel** [comment]
> when something happens that requires the user to check the log and fix something.

A user should always run `--check` after changing the config... if something in the config itself is broken this should not be a big surprise... in general this should only happen after changes.

**Comment by RedBearAK** [comment]
OK, I think I need to ask a simple question. Is the intention with this change to allow include files with problems to be bypassed while leaving an error message in the log, or is keyszer still just going to crash whenever any one of potentially dozens of include files has an issue? 

My own attempt was going to be a "try" sort of scenario, that would keep keyszer from entirely crashing just because there was a missing comma in one of the "modules" it tries to import. It would just disable whatever features that module would activate if it had passed the check.

**Comment by joshgoebel** [comment]
`include` is for convenience and organization - it's still considered a single configuration. If the config (all of it) is not valid then that is a hard error: we have NO idea what the software should be doing if we can't execute the config.

**Comment by RedBearAK** [comment]
> still considered a single configuration. If the config (all of it) is not valid then that is a hard error

A very valid point of view, and kind of what I expected you to say. You can't know how the included modules are supposed to interact with the rest of the config. And since it's all Python it creates one big "program". Quite right. It wouldn't be proper, perhaps not even safe, to run the whole program with something missing. 

Alright. So really as far as a GUI notification, that should be left up to something like the Kinto GUI that is using keyszer as a tool. It should run keyszer with `--check` and show the notification itself if keyszer gives back an error. 

So never mind about putting GUI notifications in keyszer. Doesn't make as much sense as I was thinking.

**Comment by joshgoebel** [comment]
> It should run keyszer with --check and show the notification itself if keyszer gives back an error.

That's a reasonable proposal for something like Kinto.

**Comment by joshgoebel** [comment]
> It should run keyszer with --check and show the notification itself if keyszer gives back an error.

That's a reasonable proposal for something like Kinto.

**Comment by RedBearAK** [comment]
I checked out this branch and tried to use it to include the whole OptSpecialChars scheme from a separate file. Getting an error. 

```py
FileNotFoundError: [Errno 2] No such file or directory: 'optspecialchars_US_ABC.py'
```

Path seems to be fine, although it's not displayed, since if I try to add the absolute path it gets duplicated. It obviously knows the full path. 

```py
FileNotFoundError: [Errno 2] No such file or directory: '/home/kris/.config/kinto/home/kris/.config/kinto/optspecialchars_US_ABC.py'
```

The file is definitely in the same folder as the config file I'm using. So I'm not sure what's going on just yet.

**Comment by RedBearAK** [comment]
```py
def include(file):
    dirname = os.path.dirname(file)
    print(f"############   dirname is: {dirname} ")
    # name = f"{dirname}{file}"
    name = f"/home/kris/.config/kinto/{file}"
    print(f"#################   file name is: {name} ")
```

"dirname" prints out as empty for me. Not sure how that's even supposed to work. You're asking for a relative filename but then trying to get the full path from it. 

It works fine as long as I set the path statically like this as a test. 

Shouldn't it be getting the directory name from the config file itself? I used to have something like that in my config when I was trying to use `launch()` commands. 

I think you need something like one of these, probably the second one will do the trick. I can't recall why I even had the more complicated line. I'm too tired to follow through on this right now but I can take another look at fixing this later. 

```py
# Dynamic variables, set by python function output: 
_scriptdirname = os.path.dirname(os.path.realpath(os.path.expanduser(__file__)))
_filepath = os.path.realpath(__file__)
```

**Comment by joshgoebel** [comment]
See if that's any better?

**Comment by RedBearAK** [comment]
> See if that's any better?

Works now. No problem. Planning on merging this before releasing v0.7?

**Comment by RedBearAK** [comment]
Confirmed working after switching back to main and doing a pull. 

👍🏽

**Comment by RedBearAK** [comment]
@joshgoebel 

Would you be resistant to adding something to this that tacks on a default sub-folder path if the provided relative filename doesn't exist in the same folder as the config file? 

I'm thinking it would be good to start putting all "include" files in a separate folder like "config-includes". But it would be nice not to have to add that to every `include` line that we end up putting in the config file. Just have it look in the same folder as the config file, then look in the default "config-includes" folder if the file isn't found. 

Maybe even make it a configurable option, like the timeouts, settable in the config. 

```py
timeouts(
    multipurpose = 1,           # default: 1 sec
    suspend = 0.1,              # default: 1 sec
)
includes(
    search_path = "kinto-includes",    # path to search for include module files
)
```

Make any sense?

**Comment by joshgoebel** [comment]
> Would you be resistant to adding something to this that tacks on a default sub-folder path if the provided relative filename doesn't exist in the same folder as the config file?

Yes, I think that's a pretty not-good idea.  Explicit over implicit.  If you have:

```
include "lib/UI.py"
include "lib/sublime.py"
include "lib/vim.py"
```

There is nothing wrong with repeating `lib`, it's clear and explicit.  _If you don't like it, just write/wrap your own include helper._  These small things are trivial.

**Comment by RedBearAK** [comment]
@joshgoebel 

> Explicit over implicit.

Yeah, I was thinking even when I wrote that about what would happen if the same file were in both locations. Potentially could cause a lot of user confusion. Not my best idea.

**Comment by joshgoebel** [comment]
If you hate the duplication again, helpers your friend: 😎

```py
mod "UI"
mod "sublime"
mod "vim"
```

**Pull request merged**
