### PR TITLE
[FEAT] Allows you to enter custom keys for unsupported devices

### PR DESCRIPTION
**Pull request by luizoti**
Allows you to enter custom keys for unsupported devices

**Checklist**

- [ ] Added tests (if necessary)
- [ ] Updated docs or README...

### CODE REVIEW

**Comment by joshgoebel** [comment]
What _keyboard_ device is the auto-detect rules failing to identify?

**Comment by luizoti** [comment]
> What _keyboard_ device is the auto-detect rules failing to identify?

Sorry for the delay, I didn't see the comment, PS3 BD Remote.


Controler buttons: 


    Key.ESC:              [Key.ESC, Key.ESC],
    Key.KEY_1:            [Key.KEY_1, Key.KEY_1],
    Key.KEY_2:            [Key.KEY_2, Key.KEY_2],
    Key.KEY_3:            [Key.KEY_3, Key.KEY_3],
    Key.KEY_4:            [Key.KEY_4, Key.KEY_4],
    Key.KEY_5:            [Key.KEY_5, Key.KEY_5],
    Key.KEY_6:            [Key.KEY_6, Key.KEY_6],
    Key.KEY_7:            [Key.KEY_7, Key.KEY_7],
    Key.KEY_8:            [Key.KEY_8, Key.KEY_8],
    Key.KEY_9:            [Key.KEY_9, Key.KEY_9],
    Key.KEY_0:            [Key.KEY_0, Key.KEY_0],
    Key.ENTER:            [Key.ENTER, Key.ENTER],
    Key.UP:               [Key.UP, Key.UP],
    Key.LEFT:             [Key.LEFT, Key.LEFT],
    Key.RIGHT:            [Key.RIGHT, Key.RIGHT],
    Key.DOWN:             [Key.DOWN, Key.DOWN],
    Key.PAUSE:            [Key.PLAY, Key.PLAY],
    Key.STOP:             [Key.STOP, Key.STOP],
    Key.MENU:             [Key.C, Key.C],
    Key.BACK:             [Key.BACK, Key.BACK],
    Key.FORWARD:          [Key.UP, Key.UP],
    Key.EJECTCD:          [Key.UP, Key.UP],
    Key.REWIND:           [Key.UP, Key.UP],
    Key.HOMEPAGE:         [Key.UP, Key.UP],
    Key.PLAY:             [Key.PLAY, Key.PLAY],
    Key.BTN_0:            [Key.UP, Key.UP],
    Key.BTN_TL:           [Key.UP, Key.UP],
    Key.BTN_TR:           [Key.UP, Key.UP],
    Key.BTN_TL2:          [Key.UP, Key.UP],
    Key.BTN_TR2:          [Key.UP, Key.UP],
    Key.BTN_START:        [Key.UP, Key.UP],
    Key.BTN_THUMBL:       [Key.UP, Key.UP],
    Key.BTN_THUMBR:       [Key.UP, Key.UP],
    Key.KEY_SELECT:       [Key.UP, Key.UP],
    Key.KEY_CLEAR:        [Key.UP, Key.UP],
    Key.KEY_OPTION:       [Key.UP, Key.UP],
    Key.KEY_INFO:         [Key.UP, Key.UP],
    Key.KEY_TIME:         [Key.UP, Key.UP],
    Key.KEY_SUBTITLE:     [Key.UP, Key.UP],
    Key.KEY_ANGLE:        [Key.UP, Key.UP],
    Key.KEY_SCREEN:       [Key.UP, Key.UP],
    Key.KEY_AUDIO:        [Key.UP, Key.UP],
    Key.KEY_RED:          [Key.UP, Key.UP],
    Key.KEY_GREEN:        [Key.UP, Key.UP],
    Key.KEY_YELLOW:       [Key.UP, Key.UP],
    Key.KEY_BLUE:         [Key.UP, Key.UP],
    Key.KEY_NEXT:         [Key.UP, Key.UP],
    Key.KEY_PREVIOUS:     [Key.UP, Key.UP],
    Key.KEY_FRAMEBACK:    [Key.UP, Key.UP],
    Key.KEY_FRAMEFORWARD: [Key.UP, Key.UP],
    Key.KEY_CONTEXT_MENU: [Key.UP, Key.UP],

**Comment by joshgoebel** [comment]
This is not really how we'd want people to add devices... please see #19 instead... someone should just be able to add the name of the device to their config file...

**Comment by luizoti** [comment]
It really is a simpler path, I'll think about it when I have some free time.

**Pull request closed without merging**
